model:
  detection:
    name: "db_resnet50"
    pretrained: true
    min_size: 1024
    max_size: 2048
    available_architectures:
      db_resnet50:
        description: "DBNet with ResNet-50 backbone"
        characteristics: "Good balance of accuracy and speed"
        use_case: "General purpose document detection"
      db_mobilenet_v3_large:
        description: "DBNet with MobileNetV3-Large backbone"
        characteristics: "Faster, optimized for mobile/edge devices"
        use_case: "Mobile applications, edge devices"
      linknet_resnet18:
        description: "LinkNet with ResNet-18 backbone"
        characteristics: "Fast, lightweight"
        use_case: "Real-time applications with moderate accuracy needs"
      linknet_resnet34:
        description: "LinkNet with ResNet-34 backbone"
        characteristics: "Better accuracy than ResNet-18, still relatively fast"
        use_case: "Real-time applications with higher accuracy needs"
      fast_tiny:
        description: "FAST with tiny configuration"
        characteristics: "Very fast, lowest accuracy"
        use_case: "Real-time applications with basic detection needs"
      fast_small:
        description: "FAST with small configuration"
        characteristics: "Fast, moderate accuracy"
        use_case: "Real-time applications with moderate accuracy needs"
      fast_base:
        description: "FAST with base configuration"
        characteristics: "Fast, good accuracy"
        use_case: "Real-time applications with good accuracy needs"
  recognition:
    name: "crnn_vgg16_bn"
    pretrained: true
    vocab: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    available_architectures:
      crnn_vgg16_bn:
        description: "CRNN with VGG16-BN backbone"
        characteristics: "Good accuracy, moderate speed"
        use_case: "General purpose text recognition"
      crnn_mobilenet_v3_small:
        description: "CRNN with MobileNetV3-Small backbone"
        characteristics: "Fast, optimized for mobile/edge devices"
        use_case: "Mobile applications, edge devices"
      crnn_mobilenet_v3_large:
        description: "CRNN with MobileNetV3-Large backbone"
        characteristics: "Better accuracy than small version, still fast"
        use_case: "Mobile applications requiring better accuracy"
      sar_resnet31:
        description: "SAR with ResNet-31 backbone"
        characteristics: "High accuracy, slower speed"
        use_case: "Applications requiring high accuracy"

preprocessing:
  resize:
    min_size: 1024
    max_size: 2048
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225] 